"""rerun of migrations

Revision ID: 124f6f73d049
Revises: 
Create Date: 2023-04-13 17:26:59.702661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124f6f73d049'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=260),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('thumbnail',
               existing_type=sa.VARCHAR(length=260),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=80), nullable=True))
        batch_op.alter_column('thumbnail',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=260),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=260),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('city')

    op.drop_table('authors')
    # ### end Alembic commands ###
