"""empty message

Revision ID: 2075c62c3b19
Revises: c84e96356026
Create Date: 2023-04-20 10:02:10.791170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2075c62c3b19'
down_revision = 'c84e96356026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('thumbnail',
               existing_type=sa.BLOB(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('thumbnail',
               existing_type=sa.String(length=80),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
