"""empty message

Revision ID: 47538abb4692
Revises: 22cda278b677
Create Date: 2023-04-20 15:10:26.290290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47538abb4692'
down_revision = '22cda278b677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fullname')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
